// AUTO-GENERATED by the asset pipeline — one entry per optimised image.
// Reference images by key, e.g. img('f1h2o/2024-hero').

import a69 from "./continental/cgi-balls-falling.webp";
import a70 from "./continental/cgi-carpet.webp";
import a71 from "./continental/cgi-grass-grow.webp";
import a72 from "./continental/cgi-truck.webp";
import a73 from "./continental/cgi-tyre-locations.webp";
import a75 from "./continental/sm-2024-events.webp";
import a0 from "./f1h2o/2024-hero.webp";
import a1 from "./f1h2o/2024-led-promo.webp";
import a2 from "./f1h2o/2024-social-1.webp";
import a3 from "./f1h2o/2024-social-2.webp";
import a4 from "./f1h2o/2025-promo.webp";
import a5 from "./f1h2o/2025-social-1.webp";
import a6 from "./f1h2o/2025-social-2.webp";
import a7 from "./f1h2o/2025-social-3.webp";
import a8 from "./f1h2o/2025-social-4.webp";
import a74 from "./logo/continental.webp";
import a9 from "./logo/f1h2o.webp";
import a10 from "./logo/sctda.webp";
import a11 from "./logo/shurooq.webp";
import a12 from "./logo/summer.webp";
import a13 from "./logo/visit-sharjah.webp";
import a14 from "./logo/wos.webp";
import a15 from "./portrait.webp";
import a16 from "./sctda/archway-reference.webp";
import a17 from "./sctda/logo-1-sun.webp";
import a18 from "./sctda/logo-2-government.webp";
import a19 from "./sctda/logo-3-sctda.webp";
import a20 from "./sctda/logo-reveal.webp";
import a21 from "./sctda/social-heerji.webp";
import a22 from "./sctda/social-miami.webp";
import a23 from "./sctda/social-national-day.webp";
import a24 from "./sctda/social-wtm.webp";
import a25 from "./sctda/tourism-license.webp";
import a26 from "./shurooq/2024-hero-1.webp";
import a27 from "./shurooq/2024-hero-2.webp";
import a28 from "./shurooq/2025-explainer-heera.webp";
import a29 from "./shurooq/2025-explainer-khorfakkan.webp";
import a30 from "./shurooq/2025-heera-vfx.webp";
import a31 from "./shurooq/2025-hero.webp";
import a32 from "./shurooq/2025-making-1.webp";
import a33 from "./shurooq/2025-making-2.webp";
import a34 from "./shurooq/2025-making-3.webp";
import a35 from "./shurooq/2025-making-5.webp";
import a36 from "./shurooq/2025-making-icons.webp";
import a37 from "./shurooq/2025-social-1.webp";
import a38 from "./shurooq/2025-social-2.webp";
import a39 from "./shurooq/2025-social-3.webp";
import a40 from "./shurooq/2025-social-4.webp";
import a41 from "./shurooq/2026-hero.webp";
import a42 from "./shurooq/2026-social-1.webp";
import a43 from "./shurooq/2026-social-2.webp";
import a44 from "./shurooq/2026-social-3.webp";
import a45 from "./summer/2024-assets-1.webp";
import a46 from "./summer/2024-assets-2.webp";
import a47 from "./summer/2024-assets-3.webp";
import a48 from "./summer/2024-cgi.webp";
import a49 from "./summer/2024-location-1.webp";
import a50 from "./summer/2024-location-2.webp";
import a51 from "./summer/2026-hero.webp";
import a52 from "./summer/2026-infographic.webp";
import a53 from "./summer/2026-social-1.webp";
import a54 from "./summer/2026-social-2.webp";
import a55 from "./summer/2026-social-3.webp";
import a56 from "./summer/2026-social-4.webp";
import a57 from "./tools/3ds-max.webp";
import a58 from "./tools/after-effects.webp";
import a59 from "./tools/blender.webp";
import a60 from "./tools/maya.webp";
import a61 from "./tools/premiere.webp";
import a62 from "./wos/2024-kv.webp";
import a63 from "./wos/2024-player-greetings.webp";
import a64 from "./wos/2024-teaser.webp";
import a65 from "./wos/2025-greeting-1.webp";
import a66 from "./wos/2025-greeting-2.webp";
import a67 from "./wos/2025-social-1.webp";
import a68 from "./wos/2025-social-2.webp";

export type ImageAsset = { src: string; width: number; height: number };

const assets = {
  "continental/cgi-balls-falling": { src: a69, width: 720, height: 1280 },
  "continental/cgi-carpet": { src: a70, width: 800, height: 1422 },
  "continental/cgi-grass-grow": { src: a71, width: 800, height: 1422 },
  "continental/cgi-truck": { src: a72, width: 800, height: 1422 },
  "continental/cgi-tyre-locations": { src: a73, width: 800, height: 1422 },
  "continental/sm-2024-events": { src: a75, width: 800, height: 1422 },
  "f1h2o/2024-hero": { src: a0, width: 800, height: 450 },
  "f1h2o/2024-led-promo": { src: a1, width: 800, height: 271 },
  "f1h2o/2024-social-1": { src: a2, width: 800, height: 800 },
  "f1h2o/2024-social-2": { src: a3, width: 800, height: 800 },
  "f1h2o/2025-promo": { src: a4, width: 800, height: 271 },
  "f1h2o/2025-social-1": { src: a5, width: 640, height: 800 },
  "f1h2o/2025-social-2": { src: a6, width: 640, height: 800 },
  "f1h2o/2025-social-3": { src: a7, width: 640, height: 800 },
  "f1h2o/2025-social-4": { src: a8, width: 640, height: 800 },
  "logo/continental": { src: a74, width: 710, height: 162 },
  "logo/f1h2o": { src: a9, width: 531, height: 212 },
  "logo/sctda": { src: a10, width: 747, height: 215 },
  "logo/shurooq": { src: a11, width: 700, height: 215 },
  "logo/summer": { src: a12, width: 700, height: 240 },
  "logo/visit-sharjah": { src: a13, width: 545, height: 265 },
  "logo/wos": { src: a14, width: 700, height: 257 },
  "portrait": { src: a15, width: 476, height: 476 },
  "sctda/archway-reference": { src: a16, width: 399, height: 496 },
  "sctda/logo-1-sun": { src: a17, width: 700, height: 700 },
  "sctda/logo-2-government": { src: a18, width: 1000, height: 480 },
  "sctda/logo-3-sctda": { src: a19, width: 747, height: 215 },
  "sctda/logo-reveal": { src: a20, width: 1280, height: 720 },
  "sctda/social-heerji": { src: a21, width: 720, height: 1280 },
  "sctda/social-miami": { src: a22, width: 720, height: 1280 },
  "sctda/social-national-day": { src: a23, width: 720, height: 1280 },
  "sctda/social-wtm": { src: a24, width: 720, height: 1280 },
  "sctda/tourism-license": { src: a25, width: 1280, height: 720 },
  "shurooq/2024-hero-1": { src: a26, width: 800, height: 450 },
  "shurooq/2024-hero-2": { src: a27, width: 800, height: 450 },
  "shurooq/2025-explainer-heera": { src: a28, width: 800, height: 450 },
  "shurooq/2025-explainer-khorfakkan": { src: a29, width: 800, height: 450 },
  "shurooq/2025-heera-vfx": { src: a30, width: 450, height: 800 },
  "shurooq/2025-hero": { src: a31, width: 800, height: 450 },
  "shurooq/2025-making-1": { src: a32, width: 500, height: 280 },
  "shurooq/2025-making-2": { src: a33, width: 500, height: 281 },
  "shurooq/2025-making-3": { src: a34, width: 500, height: 281 },
  "shurooq/2025-making-5": { src: a35, width: 500, height: 280 },
  "shurooq/2025-making-icons": { src: a36, width: 500, height: 264 },
  "shurooq/2025-social-1": { src: a37, width: 450, height: 800 },
  "shurooq/2025-social-2": { src: a38, width: 450, height: 800 },
  "shurooq/2025-social-3": { src: a39, width: 450, height: 800 },
  "shurooq/2025-social-4": { src: a40, width: 450, height: 800 },
  "shurooq/2026-hero": { src: a41, width: 450, height: 800 },
  "shurooq/2026-social-1": { src: a42, width: 450, height: 800 },
  "shurooq/2026-social-2": { src: a43, width: 450, height: 800 },
  "shurooq/2026-social-3": { src: a44, width: 450, height: 800 },
  "summer/2024-assets-1": { src: a45, width: 500, height: 291 },
  "summer/2024-assets-2": { src: a46, width: 373, height: 500 },
  "summer/2024-assets-3": { src: a47, width: 500, height: 253 },
  "summer/2024-cgi": { src: a48, width: 450, height: 800 },
  "summer/2024-location-1": { src: a49, width: 281, height: 500 },
  "summer/2024-location-2": { src: a50, width: 281, height: 500 },
  "summer/2026-hero": { src: a51, width: 800, height: 450 },
  "summer/2026-infographic": { src: a52, width: 450, height: 800 },
  "summer/2026-social-1": { src: a53, width: 450, height: 800 },
  "summer/2026-social-2": { src: a54, width: 450, height: 800 },
  "summer/2026-social-3": { src: a55, width: 450, height: 800 },
  "summer/2026-social-4": { src: a56, width: 450, height: 800 },
  "tools/3ds-max": { src: a57, width: 160, height: 160 },
  "tools/after-effects": { src: a58, width: 160, height: 160 },
  "tools/blender": { src: a59, width: 160, height: 131 },
  "tools/maya": { src: a60, width: 160, height: 160 },
  "tools/premiere": { src: a61, width: 160, height: 156 },
  "wos/2024-kv": { src: a62, width: 450, height: 800 },
  "wos/2024-player-greetings": { src: a63, width: 450, height: 800 },
  "wos/2024-teaser": { src: a64, width: 450, height: 800 },
  "wos/2025-greeting-1": { src: a65, width: 450, height: 800 },
  "wos/2025-greeting-2": { src: a66, width: 450, height: 800 },
  "wos/2025-social-1": { src: a67, width: 450, height: 800 },
  "wos/2025-social-2": { src: a68, width: 450, height: 800 },
} as const satisfies Record<string, ImageAsset>;

export type ImageKey = keyof typeof assets;
export function img(key: ImageKey): ImageAsset {
  return assets[key];
}
export function ratio(key: ImageKey): number {
  const a = assets[key];
  return a.width / a.height;
}
